# имя, чтобы отображалось в интерфейсе
name: Flake8

# тут список событий, на который экшен должен запускаться
on: 
 push:
 pull_request:
  branches:
   - main
   - feature

jobs:
 lint: # name od job
   runs-on: ubuntu-latest
   strategy:
     matrix:
       python-version: ["3.8"]

   steps: 
   
     - name: Clone git repository
       run: echo "Cloning git repository"
     - uses: actions/checkout@v3 #checkout
     
     - name: Install Python
       run: echo "Installing Python"       
     - uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pipenv wheel
         pip install flake8 pycodestyle
         
     - name: Check syntax bu flake 8
       # Stop the build if there are Python syntax errors or undefined names
       run: flake8 --max-line-length=88 --ignore=F541 --exclude=docs,test_environment.py
