# имя, чтобы отображалось в интерфейсе
name: Flake8

# тут список событий, на который экшен должен запускаться
on: 
 push:
 pull_request:
  branches:
   - main
   - feature

jobs:
 lint: # name od job
   runs-on: ubuntu-latest
   strategy:
     matrix:
       python-version: ["3.8"]

   steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
   
      - name: Clone git repository
        uses: actions/checkout@v3 #checkout
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
     
      - name: List files in the repository
        run: |
         ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
     
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pipenv wheel
         pip install flake8 pycodestyle
         
      - name: Check syntax bu flake 8
       # Stop the build if there are Python syntax errors or undefined names
        run: flake8 --max-line-length=88 --ignore=F541 --exclude=docs,test_environment.py
