# имя, чтобы отображалось в интерфейсе
name: Lint

# тут список событий, на который экшен должен запускаться
on:
  pull_request: # и на пулл-реквест

# список того, что нужно делать. каждый job будет выводиться отдельным элементом слева UI
jobs:
  lint: # uniqe id
    runs-on: ubuntu-latest # на какой машине гонять
    steps:  # список шагов, разберем подробнее отдельно ниже
      - uses: actions/checkout@v3 #checkout делает pull репозитория и ветки, в котором запущен
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          pip install flake8 pycodestyle

      - name: Check syntax
        # Stop the build if there are Python syntax errors or undefined names
        run: flake8 --count --statistics --show-source

      - name: Warnings
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-exclude=""
